name: Build and deploy ASP.Net Core app to Azure Web App - Eventmanagement-course

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # ---------- Build React ----------
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install deps and build React app
        run: |
          cd Frontend 
          cd client
          npm install
          npm run build

      # Copy React build into ASP.NET wwwroot
      - name: Copy React build to ASP.NET wwwroot
        shell: cmd
        run: |
          if exist BackEnd\ReactEventManagerApi\wwwroot rmdir /s /q BackEnd\ReactEventManagerApi\wwwroot
          mkdir BackEnd\ReactEventManagerApi\wwwroot
          xcopy client\build BackEnd\ReactEventManagerApi\wwwroot /E /I /Y

      # ---------- Build .NET ----------
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore BackEnd/ReactEventManagerApi/ReactEventManagerApi.csproj

      - name: Build
        run: dotnet build BackEnd/ReactEventManagerApi/ReactEventManagerApi.csproj -c Release --no-restore

      - name: Publish
        run: dotnet publish BackEnd/ReactEventManagerApi/ReactEventManagerApi.csproj -c Release -o publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: publish

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7B049FEF099F4259A9CB15829DE5D12B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0D915E302174481EA799B2452928983C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_839CB925A6674ECC90501340DAA34752 }}


      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: Eventmanagement-course
          package: .
